### ISSUE TITLE
Admin commands?

### ISSUE THREAD

**Issue by ysy960108** [darbyjack/Guilds-Plugin#88]
The admin commands usage in "/guilds help" is hard to understand. For example, I want to delete a guild but I cannot find how to do that with command.
I know there is a wiki, but the in-game message about admin command is still hard to read.

**Comment by darbyjack** [comment]
Thanks for letting me know. I'll keep this noted and make sure it's easier to understand in the rewrite!

**Comment by darbyjack** [comment]
Hey @ysy960108 I've rewritten the Admin commands so that you can understand it a lot easier now! 

Here's an example of what will show when you type /guild admin 
![image](https://user-images.githubusercontent.com/21014720/45331655-8a1d4880-b531-11e8-8b58-34e9c5ab244e.png)
Hope you like it! Let me know!
